# Permalinks
permalink: pretty

# Setup
title: Michigan AI Blog
title_image: '/public/AI-LAB.svg'
tagline:            
url: https://michiganaiblog.github.io
paginate: 1
baseurl: ""

# Assets
assets:
  sources:
   - assets/fonts
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Michigan AI
  url:               
  email: preetir@umich.edu

# Custom vars
version: 2.0.0
github:
  repo:              

pages_list:
  Subscribe: '/subscribe/'
  Archive: '/archive/'
  About: '/about/'
  # Tags: '/tags/'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
